{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sampleapp.fullname" . -}}
{{- $serviceName := include "sampleapp.name" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $serviceName }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ $servicePort }} 
{{- end }}